// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18bd8ObF62mLLnXNWSo9HEQUDGTurzT0',
    appId: '1:484926471007:web:ee83e22e85bb45520014ea',
    messagingSenderId: '484926471007',
    projectId: 'penjanje-e8699',
    authDomain: 'penjanje-e8699.firebaseapp.com',
    storageBucket: 'penjanje-e8699.firebasestorage.app',
    measurementId: 'G-1HD2SJNVQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY00LxTHvY9vzTFhuFPlM1gYTVEpUvWKc',
    appId: '1:484926471007:android:e6163dfc3ef07abf0014ea',
    messagingSenderId: '484926471007',
    projectId: 'penjanje-e8699',
    storageBucket: 'penjanje-e8699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLd_BskyK3dRzXEYYFtRtx5iCBSyct544',
    appId: '1:484926471007:ios:f6a2796dd5d683340014ea',
    messagingSenderId: '484926471007',
    projectId: 'penjanje-e8699',
    storageBucket: 'penjanje-e8699.firebasestorage.app',
    iosBundleId: 'com.example.penjanje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLd_BskyK3dRzXEYYFtRtx5iCBSyct544',
    appId: '1:484926471007:ios:f6a2796dd5d683340014ea',
    messagingSenderId: '484926471007',
    projectId: 'penjanje-e8699',
    storageBucket: 'penjanje-e8699.firebasestorage.app',
    iosBundleId: 'com.example.penjanje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18bd8ObF62mLLnXNWSo9HEQUDGTurzT0',
    appId: '1:484926471007:web:11d4690614cad20a0014ea',
    messagingSenderId: '484926471007',
    projectId: 'penjanje-e8699',
    authDomain: 'penjanje-e8699.firebaseapp.com',
    storageBucket: 'penjanje-e8699.firebasestorage.app',
    measurementId: 'G-RPGZVN6DN6',
  );
}
